name: Deploy para BunnyCDN
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy para Storage Zone
        uses: Snider/bunnycdn-gh-action@v2.0.1
        with:
          source: "."                           # pasta a enviar
          storageZoneName: ${{ secrets.BUNNY_CDN_STORAGE_ZONE_NAME }}
          accessKey:         ${{ secrets.BUNNY_CDN_STORAGE_KEY }}
          zoneId:            ${{ secrets.BUNNY_CDN_PULL_ZONE_ID }}
          zoneKey:           ${{ secrets.BUNNY_CDN_ZONE_KEY }} :contentReference[oaicite:1]{index=1}
