name: Deploy Bunny Scripting Script

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish the script to Bunny
        uses: BunnyWay/actions/deploy-script@main
        with:
          script_id: 40639
          file: "script.js"
